# Generated by Django 6.0.1 on 2026-03-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_custom404page"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Custom404Page",
            new_name="CustomErrorPage",
        ),
    ]
