# Generated by Django 6.0.1 on 2026-03-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_custom404page_customerrorpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom404Page",
            fields=[
                (
                    "customerrorpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.customerrorpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.customerrorpage",),
        ),
        migrations.CreateModel(
            name="Custom500Page",
            fields=[
                (
                    "customerrorpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.customerrorpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.customerrorpage",),
        ),
    ]
