# Generated by Django 6.0.1 on 2026-02-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filchat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filchatpage",
            old_name="intro",
            new_name="body",
        ),
    ]
